### ISSUE TITLE
Define MVP feature set

### ISSUE THREAD

**Issue by shanberg** [danielpcox/belief#5]
Once we’ve figured out a data model, we should define scope of work for the MVP, so we know what we’re getting into.

**Comment by danielpcox** [comment]
Here's what I imagine:
Each proposition is composed of a text box for an English description, a smaller textbox for your prior probability, inputs on the left, and outputs on the right. Whenever you connect the output to the input of another card, a textbox appears on that link representing the likelihood ratio (how many times more likely the receiving proposition is to be true if the sending proposition is true). It'll default to 1:1. On each proposition, there will also be a label representing the calculated probability that this proposition is true.
That's the MVP, in my mind.
When you first make a new proposition on the canvas, its calculated probability is just the prior you specify. Connecting things updates it.
Later, we'll want to have the app give you as much help as possible in coming up with these values, with things like mutually-exclusive proposition groups, visual value manipulation, causal networks, etc.
I think I can get the basic thing working probably in a single sitting. Then I'll feel like it's actually usable once we get pan/zoom and save/load in. I also feel like at that point, I'll be able to start thinking about features

**Comment by shanberg** [comment]
Completed
